name: Make Release Draft

on:
  push:
    branches:
      - master
      - github-actions

permissions:
  contents: write

jobs:
  draft-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
      - uses: actions/setup-node@v3.8.1
        with:
          node-version: 18.x
      # - name: get-package-version
      #   id: package-version
      #   uses: martinbeentjes/npm-get-version-action@v1.3.1
      - name: get-package-version
        id: package-version
        run: |
          jq -e -r ".version" package.json > temp-version
          echo "PACKAGE_VERSION="`cat temp-version` >> "$GITHUB_OUTPUT"

      # check if tag already exists
      # - run: git tag v${{steps.package-version.outputs.PACKAGE_VERSION}}
      - run: git tag -l
      - run: npm ci
      - run: npm run build
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{steps.package-version.outputs.PACKAGE_VERSION}}
          draft: true
          target_commitish: master
          files: |
            ./dist/save-manager-*.zip
